import {
  House,
  User02Icon,
  Users,
  Database,
  Activity,
  Megaphone,
  Calendar,
  Settings,
  BarChart,
  Lightning,
  Mail01Icon,
  StarIcon,
  Book01Icon,
  HandshakeIcon,
  TaskIcon,
  Files01Icon,
} from "@hugeicons/core-free-icons"

export const sidebarMenus = [
  {
    title: "Dashboard",
    icon: House,
    path: "/",
    heading: "Dashboard",
    description: "Overview of activity and key metrics across your workspace.",
  },
  {
    title: "Leads",
    icon: Users,
    path: "/leads",
    heading: "Leads",
    description: "Manage your leads and their information.",
  },
  {
    title: "Contacts",
    icon: Book01Icon,
    path: "/contacts",
    heading: "Contacts",
    description: "Manage your contacts and their information.",
  },
  {
    title: "Opportunities",
    icon: HandshakeIcon,
    path: "/opportunities",
    heading: "Opportunities",
    description: "Manage your opportunities and their information.",
  },
  {
    title: "Deals",
    icon: HandshakeIcon,
    path: "/deals",
    heading: "Deals",
    description: "Manage your deals and their information.",
  },
  {
    title: "Tasks",
    icon: TaskIcon,
    path: "/tasks",
    heading: "Tasks",
    description: "Manage your tasks and their information.",
  },
  {
    title: "Documents",
    icon: Files01Icon,
    path: "/documents",
    heading: "Documents",
    description: "Manage your documents and their information.",
  },
  {
    title: "Settings",
    icon: Settings,
    path: "/settings",
    heading: "Settings",
    description: "Manage the settings for your account and workspace.",
  },
] as const
